[repository]
authors = ["Moritz Gleissner", "Yusuf Duran"]
name = "Hypr-Which-Key"
commit_pins = [
  [
    "e93fbd7c4f991cb8ef03e433ccc4d43587923e15",
    "4b3e762e60a4a75ee0db3bd4b83f19a5ef0683d7",
  ],
  [
    "fe7b748eb668136dd0558b7c8279bfcd7ab4d759",
    "4b3e762e60a4a75ee0db3bd4b83f19a5ef0683d7",
  ],
]

[Hypr-Which-Key]
authors = ["Moritz Gleissner", "Yusuf Duran"]
description = "Which Key for hyprland"
output = "Hypr-Which-Key.so"
build = ["make all"]
