[repository]
authors = ["Moritz Gleissner", "Yusuf Duran"]
name = "Hypr-Which-Key"
commit_pins = [
  [
    "e93fbd7c4f991cb8ef03e433ccc4d43587923e15",
    "22088042ba3e794c3300ef7800a5c846762d95eb",
  ],
  [
    "fe7b748eb668136dd0558b7c8279bfcd7ab4d759",
    "22088042ba3e794c3300ef7800a5c846762d95eb",
  ],
]

[Hypr-Which-Key]
authors = ["Moritz Gleissner", "Yusuf Duran"]
description = "Which Key for hyprland"
output = "Hypr-Which-Key.so"
build = ["make all"]
