[repository]
authors = ["Moritz Gleissner", "Yusuf Duran"]
name = "Hypr-Which-Key"
commit_pins = [
  [
    "cba1ade848feac44b2eda677503900639581c3f4",
    "4b3e762e60a4a75ee0db3bd4b83f19a5ef0683d7",
  ],
]

[Hypr-Which-Key]
authors = ["Moritz Gleissner", "Yusuf Duran"]
description = "Which Key for hyprland"
output = "Hypr-Which-Key.so"
build = ["make all"]
